name: "Setup Auth0 CLI"
description: "Installs and authorizes the Auth0 CLI for use with ACUL"
inputs:
  auth0-domain:
    description: "Auth0 domain"
    required: true
  auth0-client-id:
    description: "Auth0 client ID for M2M API access"
    required: true
  auth0-client-secret:
    description: "Auth0 client secret for M2M API access"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Auth0 CLI
      shell: bash
      run: |
        echo "Installing Auth0 CLI..."
        # Use the official installer script
        curl -sSfL https://raw.githubusercontent.com/auth0/auth0-cli/main/install.sh | sh -s -- -b /usr/local/bin
        echo "Auth0 CLI installed. Version:"
        auth0 --version

    - name: Authorize Auth0 CLI using Client Credentials
      shell: bash
      env:
        AUTH0_DOMAIN: ${{ inputs.auth0-domain }}
        AUTH0_CLIENT_ID: ${{ inputs.auth0-client-id }}
        AUTH0_CLIENT_SECRET: ${{ inputs.auth0-client-secret }}
      run: |
        echo "Attempting to log in to Auth0 CLI for domain: $AUTH0_DOMAIN"
        # Log in Universal Login customization
        auth0 login \
            --domain ${{ inputs.auth0-domain }} \
            --client-id ${{ inputs.auth0-client-id }} \
            --client-secret ${{ inputs.auth0-client-secret }}
        echo "✅ Auth0 CLI authorized."
